const mainHeading=document.getElementById('main-heading');
mainHeading.textContent='Fruit World';
mainHeading.style.color='orange';
const header=document.getElementById('header');
header.style.backgroundColor='green';
header.style.borderBottom='3px solid orange';
const basketheading=document.getElementById('basket-heading');
basketheading.style.color='green';
const para=document.createElement('p');
para.innerHTML='Please visit us again';
const thanks=document.getElementById('thanks');
thanks.append(para);